# Generated by Django 4.1 on 2023-02-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team2app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='author',
        ),
    ]
