# Generated by Django 4.1.1 on 2023-02-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team2app', '0003_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='author',
            field=models.CharField(default='User', max_length=255),
        ),
    ]
